### PR TITLE
28-add-user-guide

### LINKED ISSUE #28: Update user guide

### PR DESCRIPTION
**Pull request by yyj-02**
## Which ticket does this address

- closes #28

## What problems does this solve

- Outdated user guide

## Solution/Changes

- Updated user guide

## Checklist

- [x] All tests pass locally and on CI

### CODE REVIEW

**Review by clevon-w — COMMENTED** [review]
This is the temporary UG right?

**Comment by yyj-02** [comment]
> This is the temporary UG right?
Yes boss!

**Review by panpannnnn — APPROVED** [review]
LGTM, to clarify, are we gonna do the UG in notion and then copy-pasting it here?

**Review by homuntan02 — CHANGES_REQUESTED** [review]
Mark the features as [coming soon]

**Review by homuntan02 — APPROVED** [review]
Looks good

**Pull request merged**
